config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :accounts
  resources :passwords
  resources :usernames
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :username
    belongs_to :password

    validates_uniqueness_of :username, :scope => :password , :message => "Username and password combination already exists"

    # validates_uniqueness_of :account, :scope => [:username_id, :password], :message => "Account combination already exists"
     #  validates_uniqueness_of :username_id, :scope => :passwords_id #, :message => "Account already exists"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/password.rb
class Password < ApplicationRecord
    has_many :accounts
    has_many :usernames, through: :accounts

    validates_length_of :password, :minimum => 8, :message => "Password must be at least 8 characters long"

end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/username.rb
class Username < ApplicationRecord
    has many :accounts
    has many :passwords, through: :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_password, only: %i[ show edit update destroy ]

  # GET /passwords or /passwords.json
  def index
    @passwords = Password.all
  end

  # GET /passwords/1 or /passwords/1.json
  def show
  end

  # GET /passwords/new
  def new
    @password = Password.new
  end

  # GET /passwords/1/edit
  def edit
  end

  # POST /passwords or /passwords.json
  def create
    @password = Password.new(password_params)

    respond_to do |format|
      if @password.save
        format.html { redirect_to password_url(@password), notice: "Password was successfully created." }
        format.json { render :show, status: :created, location: @password }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @password.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passwords/1 or /passwords/1.json
  def update
    respond_to do |format|
      if @password.update(password_params)
        format.html { redirect_to password_url(@password), notice: "Password was successfully updated." }
        format.json { render :show, status: :ok, location: @password }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @password.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passwords/1 or /passwords/1.json
  def destroy
    @password.destroy

    respond_to do |format|
      format.html { redirect_to passwords_url, notice: "Password was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_password
      @password = Password.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def password_params
      params.fetch(:password, {})
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:name, :image)
    end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :set_username, only: %i[ show edit update destroy ]

  # GET /usernames or /usernames.json
  def index
    @usernames = Username.all
  end

  # GET /usernames/1 or /usernames/1.json
  def show
  end

  # GET /usernames/new
  def new
    @username = Username.new
  end

  # GET /usernames/1/edit
  def edit
  end

  # POST /usernames or /usernames.json
  def create
    @username = Username.new(username_params)

    respond_to do |format|
      if @username.save
        format.html { redirect_to username_url(@username), notice: "Username was successfully created." }
        format.json { render :show, status: :created, location: @username }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @username.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usernames/1 or /usernames/1.json
  def update
    respond_to do |format|
      if @username.update(username_params)
        format.html { redirect_to username_url(@username), notice: "Username was successfully updated." }
        format.json { render :show, status: :ok, location: @username }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @username.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usernames/1 or /usernames/1.json
  def destroy
    @username.destroy

    respond_to do |format|
      format.html { redirect_to usernames_url, notice: "Username was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_username
      @username = Username.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def username_params
      params.fetch(:username, {})
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/usernames_helper.rb
module UsernamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_show.html.erb
<div id="<%= dom_id show %>">
  <p>
    <strong>Name:</strong>
    <%= show.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= show.image %>
  </p>

</div>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Show this show", @show %> |
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shows</h1>

<div id="shows">
  <% @shows.each do |show| %>
    <%= render show %>
    <p>
      <%= link_to "Show this show", show %>
    </p>
  <% end %>
</div>

<%= link_to "New show", new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @show %>

<div>
  <%= link_to "Edit this show", edit_show_path(@show) %> |
  <%= link_to "Back to shows", shows_path %>

  <%= button_to "Destroy this show", @show, method: :delete %>
</div>

app/views/usernames/_form.html.erb
<%= form_with(model: username) do |form| %>
  <% if username.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(username.errors.count, "error") %> prohibited this username from being saved:</h2>

      <ul>
        <% username.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usernames/_username.html.erb
<div id="<%= dom_id username %>">
</div>

app/views/usernames/edit.html.erb
<h1>Editing username</h1>

<%= render "form", username: @username %>

<br>

<div>
  <%= link_to "Show this username", @username %> |
  <%= link_to "Back to usernames", usernames_path %>
</div>

app/views/usernames/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Usernames</h1>

<div id="usernames">
  <% @usernames.each do |username| %>
    <%= render username %>
    <p>
      <%= link_to "Show this username", username %>
    </p>
  <% end %>
</div>

<%= link_to "New username", new_username_path %>

app/views/usernames/new.html.erb
<h1>New username</h1>

<%= render "form", username: @username %>

<br>

<div>
  <%= link_to "Back to usernames", usernames_path %>
</div>

app/views/usernames/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @username %>

<div>
  <%= link_to "Edit this username", edit_username_path(@username) %> |
  <%= link_to "Back to usernames", usernames_path %>

  <%= button_to "Destroy this username", @username, method: :delete %>
</div>